steps:
  # 1. Cài đặt và Validate trong cùng 1 step để đảm bảo có thư viện
  - name: 'python:3.11'
    id: 'Install and Validate'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        bash scripts/validate_dag.sh

  # 3. Bước DEPLOY: Nếu validate pass, thực hiện đồng bộ lên GCS (Mục 2 & 3 trong Assignment)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to GCS'
    entrypoint: 'bash'
    args: ['scripts/deploy_dag.sh']
    env:
      - '_COMPOSER_BUCKET=${_COMPOSER_BUCKET}'

  # 4. Bước TRIGGER: Tự động chạy lại DAG sau khi deploy thành công (Mục 3 trong Assignment)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Trigger Airflow DAG'
    entrypoint: 'bash'
    args: ['scripts/trigger_dag.sh']
    env:
      - '_COMPOSER_ENV_NAME=${_COMPOSER_ENV_NAME}'
      - '_LOCATION=${_LOCATION}'
      - '_DAG_ID=healthcare_etl_pipeline'

# Cấu hình log lưu vào Cloud Storage (tùy chọn)
options:
  logging: CLOUD_LOGGING_ONLY

# Biến thay thế (Substitution variables) - Bạn cần cấu hình các biến này trên Cloud Build Trigger
substitutions:
  _COMPOSER_BUCKET: 'asia-southeast1-healthcare--c5ed87e7-bucket'
  _COMPOSER_ENV_NAME: 'healthcare-composer-env' # Tên môi trường Composer của bạn
  _LOCATION: 'asia-southeast1'
